# Generated by Django 4.1.4 on 2022-12-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_profile_username_userdetails_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
