# Generated by Django 4.1.4 on 2022-12-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='login_token',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
