# Generated by Django 4.1.4 on 2022-12-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userlogin_login_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
